### ISSUE TITLE
TT-78 pretendard 웹폰트 로컬폰트로 등록하기

### ISSUE THREAD

**Issue by suhong99** [ZeroTeamTwo/frontend#8]
git checkout -b TT-78-개-폰트-등록하기

## Issue 내용 및 현황

- [x] 1 로컬폰트 등록하기

## 관련 지라 Issue 번호

- TT-78

### 선행 및 관련 이슈 해결 해야하는 Issue

- #없으면생략

### 에러 사항 및 유의점

- 로컬 폰트 uri 경우 파일시스템 기준이기 때문에 ../../public 으로 기준을 잡아야 했음
- 3가지 폰트만 등록하여서 테일윈드 class를 regular, medium, bold만 적용되도록 세팅함. extension 쓸 경우 3가지만 자동완성됨
```css
@theme {
	--font-weight-*: initial;
	--font-weight-regular: 400;
	--font-weight-medium: 500;
	--font-weight-bold: 700;
}
```
